[envs.docs]
dependencies = [
	"sphinx>=4.4.0",
	"sphinx-autodoc-typehints>=1.17.0",
	"gitchangelog>=3.0.4",
	"mako>=1.2.0",
	"importlib-metadata>=4.0.0;python_version<'3.8'",
	"tomli>=2.0.1;python_version<'3.11'",
]

[envs.docs.env-vars]
GITCHANGELOG_CONFIG_FILENAME = "docs/gitchangelog_conf.py"
GITCHANGELOG_OUTPUT_FILENAME = "docs/_generated/CHANGELOG.rst"

[envs.docs.scripts]
html = "sphinx-build -b dirhtml docs docs/_build/html"
build = [
	"gitchangelog",
	"html",
]
